language: shell
jdk: oraclejdk9
os:
- linux
- osx
- windows
script:
- "./test_universal.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_3e63a20fd24d_key -iv $encrypted_3e63a20fd24d_iv
  -in .config.enc -out .config -d
