language: shell
jdk: oraclejdk9
os:
- linux
- osx
- windows
services:
- docker
script:
- "./test_universal.sh"
env:
  global:
  - secure: VVkXrcZfX86lM2ouypPfuIrEXQXjURa30wcrJxqpkcdcEEm1uOfbz3qklqyOQToQsnE8eyw9mR5f1ipigMxsjDDFBKbkNoiFcoyTPKC4tKZtq1lqF266dKGOS6F7U0UjV1yG7+Tlo85X0p1bUX9FxAMf4IIPkQEdawq4kT76FMTXzMqb9QYV+k7WcHf7yuTwp0D6uKJBEWm96LrMqv2+BLa/UCunjsQNa7OAQg9PgHSpdQg0dpqYjQBSn5ROZzyaok2yEj/lFX/gdY9eKbLjIKhilKaAfbAE28OCwmKwdEtqi/nK5oVno42eBgrQgnH17BCYJdE5jVhKJcibaXyfQsEK6EbDic7bjSisHBJDQNWOc0Orp6zBPAlHqAM/YdvIBm8WTFMd/KYRYxii5pirNt/7N6iMAxkZQNJxCPIR2LX8KMBmRNbEOJ5koH227kCLfTAAy206pEcPZ0Z7KHIjwUnRHl9rxOYH5buIQyihLqt+i5weExuFn0fyag7wAZVe2IwNBzM3k4YmlK3/3DRpGcZJdarrJvKNGXpkjyLI8vK00N+Jitf21WuROAl0k7frMB9AnYM7uVxDSGsRXRdoo7Bc1h1AjExZRyCU4XMyvWQWwObdb8Qh+IgO88gMRPOk87E1xThO8shpzMEvDDQ3KKh3pgFBzlxPK/PmL2impOw=
  - secure: SSueDO2TzIueUjLXyWw87fDWDCq3Ad2n+p8DHae+W5ong8qBMSpIoVlu2NGMKfDOSaynLxdRfXyCs3cnpiqBidjR14YJVV7T7idyTkYVC0arRnzjo6OKpiQf7k47QtWhs5W6lxCmEzT+S51gtWyPH2GiyPczdyBuaMC4//SQBj8mk3DOkLDZAsLjiu9t6Hd3yrtP++1uLGllYhJLea1kx8ArYSSAr7hODYcqzsDy6e9d2gWXtu3yiLqd8S95j19jYKX6nwkh1M4d8aYW6Dr5VCAkX37A4RW4GQjxqG6fiyjd3E1aAi9XgqGnGsuBuIp+l1UGj0HALzgNzfbjCTZ+oP2foIreL+5qpIKg0fb9aGxThSJXRQNvzmNRmUpFXf+Qre1fL4AvFzR7mHVenITqVfKG/+2SpTn6xkcLJS7qB0a+xX1rB21kJ15h+wJ8mRZdsEPHDaUIpxsO+PJNYOgQKd41rq3ggMx+HcFHCFmJelN6qMHn79P+Z22JppRsHl+Pa4rkOUUBNnyCD5ux/znFnyOkoU1Yx2Sj9PQlWs+Pn1yvBBtrwYe8AZHhg9cWGTO6v1o9eZlPtk2mCGpf/Q8ZakyiTRiHuWMiolCgoFEHZHh/TU/I4oiW0qDvDdp0qqtaAsl23B4ieIVfstVA9u3oOSAMfqq9daVAIqWdxDS6WzE=
